// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence;

#nullable disable

namespace SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810073940_Introduce UrlMappingDeletion")]
    partial class IntroduceUrlMappingDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics-collector")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingDeletionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("UrlMappingDeletion", "analytics-collector");
                });

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Code");

                    b.ToTable("UrlMapping", "analytics-collector");
                });

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingRedirectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IpKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("OccuredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UrlMappingDeletionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlMappingId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("UrlMappingDeletionId");

                    b.HasIndex("UrlMappingId");

                    b.ToTable("UrlMappingRedirection", "analytics-collector");
                });

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingRedirectionEntity", b =>
                {
                    b.HasOne("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingDeletionEntity", null)
                        .WithMany("UrlMappingRedirections")
                        .HasForeignKey("UrlMappingDeletionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingEntity", null)
                        .WithMany("UrlMappingRedirections")
                        .HasForeignKey("UrlMappingId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingDeletionEntity", b =>
                {
                    b.Navigation("UrlMappingRedirections");
                });

            modelBuilder.Entity("SimpleUrlShortener.AnalyticsCollector.Infrastructure.Persistence.UrlMappingEntity", b =>
                {
                    b.Navigation("UrlMappingRedirections");
                });
#pragma warning restore 612, 618
        }
    }
}
