// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleUrlShortener.UrlShortener.Infrastructure;

#nullable disable

namespace SimpleUrlShortener.UrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(NoTrackingDbContext))]
    [Migration("20250202121610_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleUrlShortener.UrlShortener.Infrastructure.Entities.Url", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Code"), "hash");

                    b.HasIndex("Original");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Original"), "hash");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
