// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence;

#nullable disable

namespace SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304115312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("url-lifetime-manager")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.UrlMappingEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Code");

                    b.ToTable("UrlMapping", "url-lifetime-manager");
                });

            modelBuilder.Entity("SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.UrlMappingRedirectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccuredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlMappingEntityCode")
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("UrlMappingEntityCode");

                    b.ToTable("UrlMappingRedirection", "url-lifetime-manager");
                });

            modelBuilder.Entity("SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.UrlMappingRedirectionEntity", b =>
                {
                    b.HasOne("SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.UrlMappingEntity", null)
                        .WithMany("UrlMappingRedirections")
                        .HasForeignKey("UrlMappingEntityCode");
                });

            modelBuilder.Entity("SimpleUrlShortener.UrlLifetimeManager.Infrastructure.Persistence.UrlMappingEntity", b =>
                {
                    b.Navigation("UrlMappingRedirections");
                });
#pragma warning restore 612, 618
        }
    }
}
