// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleUrlShortener.Infrastructure;

#nullable disable

namespace SimpleUrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(NoTrackingDbContext))]
    [Migration("20250202164044_Added_UrlCreationMoment")]
    partial class Added_UrlCreationMoment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleUrlShortener.Infrastructure.Url", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Code"), "hash");

                    b.HasIndex("Original");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Original"), "hash");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("SimpleUrlShortener.Infrastructure.UrlCreationMoment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UrlId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("UrlCreationMoments");
                });

            modelBuilder.Entity("SimpleUrlShortener.Infrastructure.UrlCreationMoment", b =>
                {
                    b.HasOne("SimpleUrlShortener.Infrastructure.Url", "Url")
                        .WithMany("CreationMoments")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("SimpleUrlShortener.Infrastructure.Url", b =>
                {
                    b.Navigation("CreationMoments");
                });
#pragma warning restore 612, 618
        }
    }
}
